import substract from "date-fns/sub";
import { ADDRESS_INPUT_TYPES } from "../../../../../address-autocomplete";
import { TITLES } from "../../../../../common/constants/titles";
import { dateFormat } from "../../../../../common/utils/date";
import { AMOUNT_TYPES } from "../../../../constants/amountTypes";
import { APPLICATION_STATUSES } from "../../../../constants/applicationStatuses";
import {
  ASSET_TYPE_CATEGORIES,
  CARS_AND_LIGHT_TRUCKS,
} from "../../../../constants/assetTypes";
import { GUARANTOR_ASSET_TYPES } from "../../../../constants/guarantorAssetTypes";
import { GUARANTOR_LIABILITY_TYPES } from "../../../../constants/guarantorLiabilityTypes";
import { GUARANTOR_RESIDENTIAL_STATUSES } from "../../../../constants/guarantorResidentialStatuses";
import { MARITAL_STATUSES } from "../../../../constants/maritalStatuses";
import { REPAYMENT_TERM_OPTIONS } from "../../../../constants/repaymentTermOptions";
import { SUPPLIER_TYPES } from "../../../../constants/supplierTypes";
import { GUARANTOR_MIN_AGE } from "../../../../constants/validation";

const currentDate = new Date();
const dateOfBirth = substract(currentDate, {
  years: GUARANTOR_MIN_AGE + 7,
});
const formattedDateOfBirth = dateFormat(dateOfBirth, "yyyy-MM-dd");

export const mockApplicationResponseData = {
  data: {
    id: "65c50784-45a8-4975-8506-2849b1e50119",
    userId: 6,
    assessmentId: null,
    name: "Test Applicant Name",
    applicationNumber: "QF10362",
    status: APPLICATION_STATUSES.DRAFTED_NEW,
    submittedAt: null,
    quote: {
      id: "700960e5-ff65-4e19-9a08-60f9bf1ce6f0",
      applicationId: "65c50784-45a8-4975-8506-2849b1e50119",
      state: true,
      financeType: "CHATTEL_MORTGAGE",
      assetTypeCategory: ASSET_TYPE_CATEGORIES.CARS_AND_LIGHT_TRUCKS as string,
      assetType: CARS_AND_LIGHT_TRUCKS.PASSENGER_VEHICLES as string,
      assetManufactureYear: 2021,
      supplierType: SUPPLIER_TYPES.DEALER as string,
      isPropertyOwner: true,
      purchaseAmount: 50000,
      depositAmount: 0,
      tradeInAmount: 0,
      tradePayoutAmount: 0,
      repaymentTermOption: REPAYMENT_TERM_OPTIONS.MONTHLY as string,
      repaymentTermMonth: 60,
      balloonType: AMOUNT_TYPES.FIXED as string,
      balloonAmount: 0,
      brokerageType: AMOUNT_TYPES.FIXED as string,
      brokerageAmount: 0,
      isFinancierRateManual: false,
      baseRate: 7.5,
      includeFees: false,
      brokerOriginationFeeAmount: 0,
      brokerOriginationFeeAmountWithGst: 0,
      advanceOrArrears: "ADVANCE",
      hasStructuredPayment: false,
      structuredPaymentNthPaymentAmount: 0,
      structuredPaymentAmount: 0,
      firstInstallmentAmount: 1430.18,
      totalPaymentToBroker: 0,
      totalPaymentToBrokerWithGst: 0,
      installmentAmount: 995.68,
      applicationFee: 395,
      applicationFeeWithGst: 434.5,
      balloonNominal: 0,
      brokerageNominal: 0,
      brokerageNominalWithGst: 0,
      financierRate: 7.5,
      customerRate: 7.5,
      amountFinanced: 50000,
    },
    applicant: {
      id: "7fa28802-a315-405e-b46b-65e9e177157c",
      applicationId: "65c50784-45a8-4975-8506-2849b1e50119",
      state: true,
      abn: "66666666666",
      entityName: "Test Applicant Name",
      tradingName: "Test Applicant Trading",
      entityType: "SOLE_TRADER",
      trusteeType: null,
      trusteeName: null,
      trusteeAcn: null,
      abnRegisteredDate: "2018-01-01",
      gstRegisteredDate: "2018-01-01",
      phone: "13000000000",
      industry: "FISHERIES",
      industryType: "FISHING_BUSINESSES",
      addressInputType: ADDRESS_INPUT_TYPES.MANUAL as string,
      addressState: "VIC",
      addressStreetName: "Nicholson St",
      addressStreetNumber: "9",
      addressUnitNumber: "",
      addressSuburb: "Carlton",
      addressPostcode: "3053",
    },
    security: {
      name: "2021",
      id: "6ba521cd-8390-4472-81ef-fbf2975f59a7",
      applicationId: "65c50784-45a8-4975-8506-2849b1e50119",
      state: false,
      supplierType: SUPPLIER_TYPES.DEALER as string,
      supplierName: "",
      usageType: "",
      assetTypeCategory: ASSET_TYPE_CATEGORIES.CARS_AND_LIGHT_TRUCKS as string,
      assetType: CARS_AND_LIGHT_TRUCKS.PASSENGER_VEHICLES as string,
      securityDetailsInputType: "",
      manufactureYear: 2021,
      make: "",
      model: "",
      retailValue: 0,
      nvic: "",
      serialNumber: "",
      registrationNumber: "",
      description: "",
      actualKm: 0,
      options: [],
      modelTypeCode: "",
      manufacturerCode: "",
      familyCode: "",
      variantName: "",
      seriesCode: "",
      rrp: 0,
      trade: 0,
      retail: 0,
      kmAdjustmentTradeValue: 0,
      kmAdjustmentRetailValue: 0,
      optionsRrpValue: 0,
      optionsTradeValue: 0,
      optionsRetailValue: 0,
      adjustedRrpValue: 0,
      adjustedTradeValue: 0,
      adjustedRetailValue: 0,
    },
    note: null,
    guarantors: [],
    publicStatus: "DRAFTED",
    user: {
      id: 6,
      firstName: "Broker",
      lastName: "Tester",
      email: "broker@quest.finance",
      mobile: "+614112345678",
      client: "Quest Finance Australia Pty Ltd",
    },
  },
};

export const mockGuarantorSaveResponse1 = {
  driverLicenseNumber: "123123123",
  id: "1",
  entityId: 10024,
  state: true,
  title: "MR",
  firstName: "John",
  middleName: null,
  lastName: "Doe",
  dateOfBirth: formattedDateOfBirth,
  licenseCardNumber: "123123123",
  driverLicenseState: "NSW",
  maritalStatus: "MARRIED",
  dependentNumber: 0,
  mobile: "0410120411",
  email: "john.doe@email.com",
  isAddressSameAsApplicant: false,
  residentialStatus: "OWNING",
  assets: [
    {
      type: "CASH",
      amount: 5000,
    },
    {
      type: "VEHICLE",
      amount: 5000,
    },
    {
      type: "INVESTMENT_PROPERTY",
      amount: 175000,
    },
  ],
  liabilities: [
    {
      type: "PERSONAL_LOAN",
      amount: 25000,
    },
    {
      type: "CREDIT_CARD",
      amount: 25000,
    },
  ],
  addressInputType: "MANUAL",
  addressState: "NSW",
  addressStreetName: "X",
  addressStreetNumber: "1",
  addressUnitNumber: "1",
  addressSuburb: "Y",
  addressPostcode: "2000",
  applicationId: mockApplicationResponseData.data.id,
  investmentPropertyAddressInputType: "MANUAL",
  investmentPropertyAddressState: "NSW",
  investmentPropertyAddressStreetName: "InvestmentX",
  investmentPropertyAddressStreetNumber: "2",
  investmentPropertyAddressUnitNumber: "24",
  investmentPropertyAddressSuburb: "InvestmentS",
  investmentPropertyAddressPostcode: "4000",
  updatedAt: "2021-11-11T11:28:47.747Z",
  createdAt: "2021-11-11T11:28:47.747Z",
};

export const mockGuarantorSaveResponse2 = {
  driverLicenseNumber: "123123123",
  id: "2",
  entityId: 10025,
  state: true,
  title: "MRS",
  firstName: "Jane",
  middleName: null,
  lastName: "Doe",
  dateOfBirth: formattedDateOfBirth,
  driverLicenseState: "NSW",
  licenseCardNumber: "123123123",
  maritalStatus: "MARRIED",
  dependentNumber: 1,
  mobile: "0410120412",
  email: "jane.doe@email.com",
  isAddressSameAsApplicant: false,
  residentialStatus: "OWNING",
  assets: [
    {
      type: "CASH",
      amount: 175000,
    },
  ],
  liabilities: [
    {
      type: "MORTGAGE",
      amount: 15330,
    },
  ],
  addressInputType: "MANUAL",
  addressState: "NSW",
  addressStreetName: "X",
  addressStreetNumber: "1",
  addressUnitNumber: "1",
  addressSuburb: "Y",
  addressPostcode: "2000",
  investmentPropertyAddressInputType: "AUTOCOMPLETE",
  investmentPropertyAddressState: "",
  investmentPropertyAddressStreetName: "",
  investmentPropertyAddressStreetNumber: "",
  investmentPropertyAddressUnitNumber: "",
  investmentPropertyAddressSuburb: "",
  investmentPropertyAddressPostcode: "",
  applicationId: mockApplicationResponseData.data.id,
  updatedAt: "2021-11-11T12:15:24.791Z",
  createdAt: "2021-11-11T12:15:24.791Z",
};

export const guarantor1 = {
  title: TITLES.MR as string,
  firstName: "John",
  middleName: null,
  lastName: "Doe",
  dateOfBirth: formattedDateOfBirth,
  driverLicenseNumber: "123123123",
  licenseCardNumber: "123123123",
  driverLicenseState: "NSW",
  maritalStatus: MARITAL_STATUSES.MARRIED as string,
  dependentNumber: 0,
  mobile: "0410120411",
  email: "john.doe@email.com",
  isAddressSameAsApplicant: false,
  residentialStatus: GUARANTOR_RESIDENTIAL_STATUSES.OWNING,
  assets: [
    {
      type: GUARANTOR_ASSET_TYPES.CASH as string,
      amount: 5000,
    },
    {
      type: GUARANTOR_ASSET_TYPES.VEHICLE as string,
      amount: 5000,
    },
    {
      type: GUARANTOR_ASSET_TYPES.INVESTMENT_PROPERTY as string,
      amount: 175000,
    },
  ],
  liabilities: [
    {
      type: GUARANTOR_LIABILITY_TYPES.PERSONAL_LOAN as string,
      amount: 25000,
    },
    {
      type: GUARANTOR_LIABILITY_TYPES.CREDIT_CARD as string,
      amount: 25000,
    },
  ],
  id: null,
  addressInputType: ADDRESS_INPUT_TYPES.MANUAL,
  addressState: "NSW",
  addressStreetName: "X",
  addressStreetNumber: "1",
  addressUnitNumber: "1",
  addressSuburb: "Y",
  addressPostcode: "2000",
  investmentPropertyAddressInputType: ADDRESS_INPUT_TYPES.MANUAL,
  investmentPropertyAddressState: "NSW",
  investmentPropertyAddressStreetName: "InvestmentX",
  investmentPropertyAddressStreetNumber: "2",
  investmentPropertyAddressUnitNumber: "24",
  investmentPropertyAddressSuburb: "InvestmentS",
  investmentPropertyAddressPostcode: "4000",
};

export const guarantor2 = {
  title: TITLES.MRS as string,
  firstName: "Jane",
  middleName: null,
  lastName: "Doe",
  dateOfBirth: formattedDateOfBirth,
  driverLicenseNumber: "123123123",
  licenseCardNumber: "",
  driverLicenseState: "NSW",
  maritalStatus: MARITAL_STATUSES.MARRIED as string,
  dependentNumber: 1,
  mobile: "0410120412",
  email: "jane.doe@email.com",
  isAddressSameAsApplicant: false,
  residentialStatus: GUARANTOR_RESIDENTIAL_STATUSES.OWNING,
  assets: [
    {
      type: GUARANTOR_ASSET_TYPES.CASH as string,
      amount: 175000,
    },
  ],
  liabilities: [
    {
      type: GUARANTOR_LIABILITY_TYPES.MORTGAGE as string,
      amount: 15330,
    },
  ],
  id: null,
  addressInputType: ADDRESS_INPUT_TYPES.MANUAL,
  addressState: "NSW",
  addressStreetName: "X",
  addressStreetNumber: "1",
  addressUnitNumber: "1",
  addressSuburb: "Y",
  addressPostcode: "2000",
  investmentPropertyAddressInputType: ADDRESS_INPUT_TYPES.AUTOCOMPLETE,
  investmentPropertyAddressState: "",
  investmentPropertyAddressStreetName: "",
  investmentPropertyAddressStreetNumber: "",
  investmentPropertyAddressUnitNumber: "",
  investmentPropertyAddressSuburb: "",
  investmentPropertyAddressPostcode: "",
};

export type GuarantorData = typeof guarantor1 | typeof guarantor2;

export const applicantAddressInput = {
  addressInputType: ADDRESS_INPUT_TYPES.MANUAL,
  addressState: "NSW",
  addressStreetName: "Applicant Street",
  addressStreetNumber: "2",
  addressUnitNumber: "12",
  addressSuburb: "Applicant Suburb",
  addressPostcode: "3000",
};
