import { ADDRESS_INPUT_TYPES } from "../../../../../address-autocomplete";
import { AMOUNT_TYPES } from "../../../../constants/amountTypes";
import { APPLICATION_STATUSES } from "../../../../constants/applicationStatuses";
import {
  ASSET_TYPE_CATEGORIES,
  CARS_AND_LIGHT_TRUCKS,
} from "../../../../constants/assetTypes";
import { REPAYMENT_TERM_OPTIONS } from "../../../../constants/repaymentTermOptions";
import { SUPPLIER_TYPES } from "../../../../constants/supplierTypes";
import { noteResponseDefaultValue } from "../../../../types/NoteResponse";

export const application = {
  id: "65c50784-45a8-4975-8506-2849b1e50119",
  userId: 6,
  assessmentId: null,
  name: "Test Applicant Name",
  applicationNumber: "QF10362",
  status: APPLICATION_STATUSES.DRAFTED_NEW,
  submittedAt: null,
  quote: {
    id: "700960e5-ff65-4e19-9a08-60f9bf1ce6f0",
    applicationId: "65c50784-45a8-4975-8506-2849b1e50119",
    state: true,
    financeType: "CHATTEL_MORTGAGE",
    assetTypeCategory: (ASSET_TYPE_CATEGORIES.CARS_AND_LIGHT_TRUCKS as string) as string,
    assetType: (CARS_AND_LIGHT_TRUCKS.PASSENGER_VEHICLES as string) as string,
    assetManufactureYear: 2021,
    supplierType: (SUPPLIER_TYPES.DEALER as string) as string,
    isPropertyOwner: true,
    purchaseAmount: 50000,
    depositAmount: 0,
    tradeInAmount: 0,
    tradePayoutAmount: 0,
    repaymentTermOption: REPAYMENT_TERM_OPTIONS.MONTHLY as string,
    repaymentTermMonth: 60,
    balloonType: AMOUNT_TYPES.FIXED as string,
    balloonAmount: 0,
    brokerageType: AMOUNT_TYPES.FIXED as string,
    brokerageAmount: 0,
    isFinancierRateManual: false,
    baseRate: 7.5,
    includeFees: false,
    brokerOriginationFeeAmount: 0,
    brokerOriginationFeeAmountWithGst: 0,
    advanceOrArrears: "ADVANCE",
    hasStructuredPayment: false,
    structuredPaymentNthPaymentAmount: 0,
    structuredPaymentAmount: 0,
    firstInstallmentAmount: 1430.18,
    totalPaymentToBroker: 0,
    totalPaymentToBrokerWithGst: 0,
    installmentAmount: 995.68,
    applicationFee: 395,
    applicationFeeWithGst: 434.5,
    balloonNominal: 0,
    brokerageNominal: 0,
    brokerageNominalWithGst: 0,
    financierRate: 7.5,
    customerRate: 7.5,
    amountFinanced: 50000,
  },
  applicant: {
    id: "7fa28802-a315-405e-b46b-65e9e177157c",
    applicationId: "65c50784-45a8-4975-8506-2849b1e50119",
    state: true,
    abn: "66666666666",
    entityName: "Test Applicant Name",
    tradingName: "Test Applicant Trading",
    entityType: "SOLE_TRADER",
    trusteeType: null,
    trusteeName: null,
    trusteeAcn: null,
    abnRegisteredDate: "2018-01-01",
    gstRegisteredDate: "2018-01-01",
    phone: "0465555555",
    industry: "FISHERIES",
    industryType: "FISHING_BUSINESSES",
    addressInputType: ADDRESS_INPUT_TYPES.AUTOCOMPLETE as string,
    addressState: "VIC",
    addressStreetName: "Nicholson St",
    addressStreetNumber: "9",
    addressUnitNumber: "",
    addressSuburb: "Carlton",
    addressPostcode: "3053",
  },
  security: {
    name: "2021",
    id: "6ba521cd-8390-4472-81ef-fbf2975f59a7",
    applicationId: "65c50784-45a8-4975-8506-2849b1e50119",
    state: true,
    supplierType: SUPPLIER_TYPES.DEALER as string,
    supplierName: "",
    usageType: "",
    assetTypeCategory: ASSET_TYPE_CATEGORIES.CARS_AND_LIGHT_TRUCKS as string,
    assetType: CARS_AND_LIGHT_TRUCKS.PASSENGER_VEHICLES as string,
    securityDetailsInputType: "",
    manufactureYear: 2021,
    make: "",
    model: "",
    retailValue: 0,
    nvic: "",
    serialNumber: "",
    registrationNumber: "",
    description: "",
    actualKm: 0,
    options: [],
    modelTypeCode: "",
    manufacturerCode: "",
    familyCode: "",
    variantName: "",
    seriesCode: "",
    rrp: 0,
    trade: 0,
    retail: 0,
    kmAdjustmentTradeValue: 0,
    kmAdjustmentRetailValue: 0,
    optionsRrpValue: 0,
    optionsTradeValue: 0,
    optionsRetailValue: 0,
    adjustedRrpValue: 0,
    adjustedTradeValue: 0,
    adjustedRetailValue: 0,
  },
  note: noteResponseDefaultValue,
  guarantors: [
    {
      driverLicenseNumber: "5343534",
      id: "c063d72a-f8cf-4e87-85d5-7cf3662a8d56",
      applicationId: "65c50784-45a8-4975-8506-2849b1e50119",
      state: true,
      title: "MR",
      firstName: "John",
      middleName: null,
      lastName: "Doe",
      dateOfBirth: new Date("1995-02-16T17:00:00.000Z"),
      driverLicenseState: "NSW",
      maritalStatus: "MARRIED",
      dependentNumber: 1,
      mobile: "0416555555",
      email: "john.doe@customemail.com",
      isAddressSameAsApplicant: true,
      residentialStatus: "OWNING",
      addressInputType: ADDRESS_INPUT_TYPES.AUTOCOMPLETE as string,
      addressState: "VIC",
      addressStreetName: "Nicholson St",
      addressStreetNumber: "9",
      addressUnitNumber: "",
      addressSuburb: "Carlton",
      addressPostcode: "3053",
      assets: [
        {
          type: "PROPERTY",
          amount: 56000,
        },
        {
          type: "INVESTMENT_PROPERTY",
          amount: 152000,
        },
      ],
      liabilities: [
        {
          type: "CREDIT_CARD",
          amount: 58000,
        },
      ],
    },
    {
      driverLicenseNumber: "65656565",
      id: "693b4546-47c0-4283-9de6-5765b370b89c",
      applicationId: "65c50784-45a8-4975-8506-2849b1e50119",
      state: true,
      title: "MRS",
      firstName: "Jane",
      middleName: null,
      lastName: "Doe",
      dateOfBirth: new Date("1988-08-16T17:00:00.000Z"),
      driverLicenseState: "NSW",
      maritalStatus: "MARRIED",
      dependentNumber: 1,
      mobile: "0456666666",
      email: "jane.doe@customemail.com",
      isAddressSameAsApplicant: true,
      residentialStatus: "OWNING",
      addressInputType: ADDRESS_INPUT_TYPES.AUTOCOMPLETE as string,
      addressState: "VIC",
      addressStreetName: "Nicholson St",
      addressStreetNumber: "9",
      addressUnitNumber: "",
      addressSuburb: "Carlton",
      addressPostcode: "3053",
      assets: [
        {
          type: "CASH",
          amount: 56000,
        },
        {
          type: "VEHICLE",
          amount: 45000,
        },
        {
          type: "INVESTMENT_PROPERTY",
          amount: 75000,
        },
      ],
      liabilities: [
        {
          type: "PERSONAL_LOAN",
          amount: 12500,
        },
      ],
    },
  ],
  publicStatus: "DRAFTED",
  user: {
    id: 6,
    firstName: "Broker",
    lastName: "Tester",
    email: "broker@quest.finance",
    mobile: "+614112345678",
    client: "Quest Finance Australia Pty Ltd",
  },
};

export const notes = {
  applicationId: "e481422b-ad00-4f21-9a55-5ffb627f4898",
  createdAt: "2021-11-11T09:15:02.587Z",
  hasApplicantConsent: true,
  hasBrokerConsent: true,
  hasForeseeableFinancialChange: false,
  id: "ec82a075-6e6d-4034-b97f-00531e7ff127",
  state: true,
  supportingNotes: "Notes",
  updatedAt: "2021-11-11T09:15:02.587Z",
};

export const requiredDocuments = {
  supportingInfo: "",
  bankStatementRequired: true,
  bankStatementLink: "https://scv-test.bankstatements.com.au/QUST-QF14262",
};

export const downloadFileResponse = {
  data: "http://testFilesServer.com",
};

export const supportingDocument = {
  id: "3e8dc4e4-a10f-457b-afa7-001537bf3a21",
  applicationId: "e481422b-ad00-4f21-9a55-5ffb627f4898",
  purpose: "SUPPORTING_DOCUMENT",
  type: "NOTE",
  filename: "supporting-doc-b5be197f.docx",
  originalFilename: "supporting-doc.docx",
  versionNumber: null,
  securedSigningId: null,
  createdAt: "2021-11-11T10:47:51.559Z",
  updatedAt: "2021-11-11T10:47:51.559Z",
  deletedAt: null,
};

export const supportingDocuments = Array.from({ length: 5 }, (v, k) => {
  return {
    ...supportingDocument,
    id: supportingDocument.id + k,
    applicationId: supportingDocument.applicationId + k,
    filename: `doc-${k}.docx`,
    originalFilename: `orig-doc-${k}.docx`,
  };
});
